import { Component, OnInit } from '@angular/core';import { CommonModule } from '@angular/common';import { AbstractControl, FormArray, FormBuilder, ReactiveFormsModule, ValidationErrors, Validators } from '@angular/forms';import { DirtyFormComponent } from './unsaved-changes.guard';
export function noCourseCode(c:AbstractControl):ValidationErrors|null{return String(c.value||'').startsWith('XX')?{noCourseCode:true}:null;}
export function simulateEmailCheck(c:AbstractControl):Promise<ValidationErrors|null>{return new Promise(r=>setTimeout(()=>r(String(c.value||'').includes('test@')?{emailTaken:true}:null),800));}
@Component({standalone:true,imports:[CommonModule,ReactiveFormsModule],template:`<div class="container"><h1>Reactive Enrollment</h1><form [formGroup]="enrollForm" (ngSubmit)="submit()"><input formControlName="studentName" placeholder="Student name"><input formControlName="studentEmail" placeholder="Email"><span class="error" *ngIf="enrollForm.get('studentEmail')?.errors?.['emailTaken']">Email taken</span><input formControlName="courseId" placeholder="Course code"><span class="error" *ngIf="enrollForm.get('courseId')?.errors?.['noCourseCode']">Course code starting with XX is not allowed.</span><select formControlName="preferredSemester"><option>Odd</option><option>Even</option></select><label><input type="checkbox" formControlName="agreeToTerms">Agree</label><div><button type="button" (click)="addCourse()">Add Another Course</button><div *ngFor="let ctrl of additionalCourses.controls;let i=index"><input [formControl]="ctrl"><button type="button" (click)="removeCourse(i)">Remove</button></div></div><button type="submit" [disabled]="enrollForm.invalid">Submit</button></form></div>`})
export class ReactiveEnrollmentFormComponent implements OnInit,DirtyFormComponent {
 enrollForm=this.fb.group({studentName:['',[Validators.required,Validators.minLength(3)]],studentEmail:this.fb.control('',[Validators.required,Validators.email],[simulateEmailCheck]),courseId:['',[Validators.required,noCourseCode]],preferredSemester:['Odd',Validators.required],agreeToTerms:[false,Validators.requiredTrue],additionalCourses:this.fb.array([])});
 constructor(private fb:FormBuilder){} ngOnInit(){}
 get additionalCourses(){return this.enrollForm.get('additionalCourses') as FormArray;} // Typed getter avoids casts in the template.
 addCourse(){this.additionalCourses.push(this.fb.control('',Validators.required));} removeCourse(i:number){this.additionalCourses.removeAt(i);}
 submit(){console.log(this.enrollForm.value,this.enrollForm.getRawValue()); /* value excludes disabled controls; getRawValue includes them. */}
 isDirty(){return this.enrollForm.dirty;}
}